name: harbor-build-upload
run-name: Deploy stage (${{ github.ref_name }})
on:
  workflow_dispatch:
    inputs:
      github_repo_name:
        description: 'Name of the github repo to build'
        required: true
      branch:
        description: 'Name of the github branch'
        required: false
        default: 'main'
      dockerfile:
        description: 'Path to the dockerfile'
        required: false
        default: 'Dockerfile'
      image_name:
        description: 'Name of the docker image'
        required: true
      image_tag:
        description: 'Tag of docker image'
        required: false
        default: 'latest'
      harbor_project:
        description: 'Name of the harbor project'
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Git Repo
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.github_repo_name }}
          token: ${{ secrets.ADMIN_TOKEN }}
          ref: ${{ inputs.branch }}
      # Build Docker Image
      - name: Build image
        run: docker build -t ${{ inputs.image_name }} -f ${{ inputs.dockerfile }} .

      - name: Docker login
        uses: docker/login-action@v2.2.0
        with:
          registry: 'harbor.pumpkinhouse.io'
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
    
      # Upload Image to Harbor Instance
      - name: Upload image
        run: |
          TARGET=harbor.pumpkinhouse.io/${{ inputs.harbor_project }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          docker tag ${{ inputs.image_name }} $TARGET
          docker push $TARGET
